/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kdu.gui;

import javax.swing.ImageIcon;

/**
 *
 * @author Lasitha
 */
public class Tempo extends javax.swing.JFrame {

    /**
     * Creates new form MusicGenerate
     */
    public Tempo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TempoWindowPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JLabel();
        okButton = new javax.swing.JLabel();
        tempoValue = new javax.swing.JLabel();
        tempoHighBtn = new javax.swing.JLabel();
        tempoLowBtn = new javax.swing.JLabel();
        TempoWindowBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(467, 290));

        TempoWindowPanel.setLayout(null);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kdu/gui/images/cancel button.png"))); // NOI18N
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });
        TempoWindowPanel.add(cancelButton);
        cancelButton.setBounds(230, 200, 100, 40);

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kdu/gui/images/ok button.PNG"))); // NOI18N
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButtonMouseReleased(evt);
            }
        });
        TempoWindowPanel.add(okButton);
        okButton.setBounds(110, 200, 100, 40);

        tempoValue.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        tempoValue.setForeground(new java.awt.Color(255, 153, 0));
        tempoValue.setText("100");
        TempoWindowPanel.add(tempoValue);
        tempoValue.setBounds(160, 120, 130, 60);

        tempoHighBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kdu/gui/images/up tempo button.PNG"))); // NOI18N
        tempoHighBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tempoHighBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tempoHighBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tempoHighBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tempoHighBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tempoHighBtnMouseReleased(evt);
            }
        });
        TempoWindowPanel.add(tempoHighBtn);
        tempoHighBtn.setBounds(310, 120, 60, 60);

        tempoLowBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kdu/gui/images/down tempo button.PNG"))); // NOI18N
        tempoLowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tempoLowBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tempoLowBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tempoLowBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tempoLowBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tempoLowBtnMouseReleased(evt);
            }
        });
        TempoWindowPanel.add(tempoLowBtn);
        tempoLowBtn.setBounds(70, 120, 60, 60);

        TempoWindowBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kdu/gui/images/Tempo window.png"))); // NOI18N
        TempoWindowPanel.add(TempoWindowBack);
        TempoWindowBack.setBounds(0, 0, 450, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TempoWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TempoWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempoHighBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoHighBtnMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("images/up tempo button hover.png"));
        tempoHighBtn.setIcon(hover);
    }//GEN-LAST:event_tempoHighBtnMouseEntered

    private void tempoHighBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoHighBtnMouseExited
        ImageIcon normal = new ImageIcon(getClass().getResource("images/up tempo button.png"));
        tempoHighBtn.setIcon(normal);
    }//GEN-LAST:event_tempoHighBtnMouseExited

    private void tempoHighBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoHighBtnMousePressed
        ImageIcon hover = new ImageIcon(getClass().getResource("images/up tempo button pressed.png"));
        tempoHighBtn.setIcon(hover);
    }//GEN-LAST:event_tempoHighBtnMousePressed

    private void tempoHighBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoHighBtnMouseReleased
        ImageIcon normal = new ImageIcon(getClass().getResource("images/up tempo button.png"));
        tempoHighBtn.setIcon(normal);
    }//GEN-LAST:event_tempoHighBtnMouseReleased

    private void tempoLowBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoLowBtnMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("images/down tempo button hover.png"));
        tempoLowBtn.setIcon(hover);
    }//GEN-LAST:event_tempoLowBtnMouseEntered

    private void tempoLowBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoLowBtnMouseExited
        ImageIcon normal = new ImageIcon(getClass().getResource("images/down tempo button.png"));
        tempoLowBtn.setIcon(normal);
    }//GEN-LAST:event_tempoLowBtnMouseExited

    private void tempoLowBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoLowBtnMousePressed
        ImageIcon hover = new ImageIcon(getClass().getResource("images/down tempo button pressed.png"));
        tempoLowBtn.setIcon(hover);
    }//GEN-LAST:event_tempoLowBtnMousePressed

    private void tempoLowBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoLowBtnMouseReleased
        ImageIcon normal = new ImageIcon(getClass().getResource("images/down tempo button.png"));
        tempoLowBtn.setIcon(normal);
    }//GEN-LAST:event_tempoLowBtnMouseReleased

    private void tempoHighBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoHighBtnMouseClicked
        int value = Integer.parseInt(tempoValue.getText());
        value = value + 1;
        tempoValue.setText(Integer.toString(value));
    }//GEN-LAST:event_tempoHighBtnMouseClicked

    private void tempoLowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoLowBtnMouseClicked
        int value = Integer.parseInt(tempoValue.getText());
        value = value - 1;
        tempoValue.setText(Integer.toString(value));
    }//GEN-LAST:event_tempoLowBtnMouseClicked

    private void okButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("images/ok button hover.png"));
        okButton.setIcon(hover);
    }//GEN-LAST:event_okButtonMouseEntered

    private void okButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseExited
        ImageIcon normal = new ImageIcon(getClass().getResource("images/ok button.png"));
        okButton.setIcon(normal);
    }//GEN-LAST:event_okButtonMouseExited

    private void okButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMousePressed
        ImageIcon hover = new ImageIcon(getClass().getResource("images/ok button pressed.png"));
        okButton.setIcon(hover);
    }//GEN-LAST:event_okButtonMousePressed

    private void okButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseReleased
        ImageIcon normal = new ImageIcon(getClass().getResource("images/ok button.png"));
        okButton.setIcon(normal);
    }//GEN-LAST:event_okButtonMouseReleased

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("images/cancel button hover.png"));
        cancelButton.setIcon(hover);
    }//GEN-LAST:event_cancelButtonMouseEntered

    private void cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseExited
        ImageIcon normal = new ImageIcon(getClass().getResource("images/cancel button.png"));
        cancelButton.setIcon(normal);
    }//GEN-LAST:event_cancelButtonMouseExited

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMousePressed
        ImageIcon hover = new ImageIcon(getClass().getResource("images/cancel button pressed.png"));
        cancelButton.setIcon(hover);
    }//GEN-LAST:event_cancelButtonMousePressed

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        ImageIcon normal = new ImageIcon(getClass().getResource("images/cancel button.png"));
        cancelButton.setIcon(normal);
    }//GEN-LAST:event_cancelButtonMouseReleased

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_okButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tempo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TempoWindowBack;
    private javax.swing.JPanel TempoWindowPanel;
    private javax.swing.JLabel cancelButton;
    private javax.swing.JLabel okButton;
    private javax.swing.JLabel tempoHighBtn;
    private javax.swing.JLabel tempoLowBtn;
    private javax.swing.JLabel tempoValue;
    // End of variables declaration//GEN-END:variables
}
